repo: https://github.com/Telecominfraproject/wlan-ap.git
branch: main
git_clone_dir: wlan-ap
openwrt_root_dir: wlan-ap/openwrt
revision: c6e0384f2116abb28d5dbbdf95bd75e18c5df23a

patch_folders:
  - patches-wlan-ap-5.4

files_folders:
  - files-wlan-ap-5.4/

wlan_ap: true
next: true
